### ISSUE TITLE
don't gate text 1.1 behind a flag, please

### ISSUE THREAD

**Issue by cartazio** [fpco/text-stream-decode#1]
it means that when try to install pandoc as a lib, cabal tries to downgrade my version of text for no reasons

have you considered using a disjunction, i thought we could do those with cabal!

**Comment by cartazio** [comment]
i suppose this is probably motivated by how the solver currently gives up on certain constraints? Another example for why cabal-install needs an SMT solver?

**Comment by snoyberg** [comment]
AFAIK, what I've put into the cabal file is the only way to tell cabal "if you're using X version of a dependency, then change the module list to include Y." If you know another way to do it, please let me know. I don't like using flags for this either.

**Comment by cartazio** [comment]
you can just use `||`

see this example in constraints from Agda.cabal

`mtl >= 2.0 && < 2.1 || >= 2.1.1 && < 2.2,`
i'm embarrased that i forgot about that

**Comment by snoyberg** [comment]
But that doesn't address the goal in the cabal file. I'm trying to include some modules conditionally: if they are provided by text 1.1, then use text's version. Otherwise, use the local copy. I don't think `||` will allow for that.

**Comment by cartazio** [comment]
gahhh. Ok. So the current issue boils down to Cabal's solver being dumb. So until cabal gets an SMT solver.. we need to figure out some work arounds!

So one question is: 
- is it possible to do a postconfigure setup.hs hook that adds those modules if the text version is < 1.1 ?

for some reason at least my cabal-install didn't discover setting the right flag, and I _imagine_ that this would be an issue for others too

**Comment by snoyberg** [comment]
I think this should be reported to the Cabal maintainers. I know @tibbe recently asked me for examples of solver problems.

**Comment by cartazio** [comment]
jah. I think there was a mailing list thread on this a few days ago

**Comment by nikuda** [comment]
Any progress on this? I'm unable to install yesod-bin because of this issue at the moment.

**Comment by snoyberg** [comment]
I actually moved this code into the streaming-commons package, and specifically did _not_ include the text11 flag to avoid this issue. If you run `cabal install yesod yesod-bin` (without using yesod-platform), it should automatically choose the new streaming-commons package instead. I'll do a yesod-platform release hopefully today.
